allow-uncaught: false
async-only: false
bail: false
check-leaks: false
color: true
delay: false
diff: true
exit: false # could be expressed as "no-exit: true"
extension:
  - js
# fgrep and grep are mutually exclusive
# fgrep: something
#file:
#  - ./lib/test/**/*.js
forbid-only: false
forbid-pending: false
full-trace: false
global: []
# fgrep and grep are mutually exclusive
# grep: something
growl: false
ignore: []
inline-diffs: false
# needs to be used with grep or fgrep
# invert: false
recursive: true
reporter: spec
reporter-option: []
#require: 
retries: 1
slow: 75
sort: false
spec: lib/test/**/*.js # the positional arguments!
timeout: false # same as "no-timeout: true" or "timeout: 0"
trace-warnings: true # node flags ok
ui: bdd
v8-stack-trace-limit: 100 # V8 flags are prepended with "v8-"
watch: false
watch-files:
  #- 'lib/**/*.js'
  #- 'test/**/*.js'
watch-ignore:
  # - 'lib/vendor'